-- Imvelaphi learner accounts
-- Run this in the Supabase SQL Editor before starting the LMS server.
-- Passwords must be stored as bcrypt hashes generated by the server.

create table if not exists public.users (
  id varchar(64) primary key,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  age integer,
  gender varchar(50),
  location varchar(150),
  email varchar(190) not null,
  password_hash varchar(255) not null,
  role varchar(20) not null default 'student',
  created_at timestamptz not null default now(),
  constraint users_email_unique unique (email),
  constraint users_role_check check (role in ('student', 'lecturer', 'admin')),
  constraint users_age_check check (age is null or age between 1 and 120)
);

create unique index if not exists users_email_lower_idx
  on public.users (lower(email));

alter table public.users enable row level security;

-- The LMS server connects with DATABASE_URL and performs registration/login
-- queries directly. Do not allow anonymous clients to read password hashes.
-- No public policies are added intentionally.

-- Registration creates student accounts only. Lecturer/admin accounts are
-- created by protected server routes or seeded by an administrator.
